apiVersion: v1
kind: Service
metadata:
  name: goland-app-service
  namespace: golang
spec:
  type: LoadBalancer
  selector:
    app: goland-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

